### ISSUE TITLE
problem building tests on master

### ISSUE THREAD

**Issue by Laeeth** [kaleidicassociates/autowrap#1]
dub test leads to 

/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/any.d(59,20): Error: undefined identifier theGC
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/any.d(60,20): Error: undefined identifier theGC
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/any.d(61,20): Error: undefined identifier theGC
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/any.d(66,25): Error: undefined identifier theGC
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/any.d(67,25): Error: undefined identifier theGC
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/any.d(68,25): Error: undefined identifier theGC
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/sdk/xll.d(43,6): Error: no property shouldEqual for type int
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/sdk/xll.d(51,30): Error: no property shouldEqual for type int
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/test/util.d(400,14): Error: no property shouldEqual for type int
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/test/util.d(401,14): Error: no property shouldEqual for type int
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/wrap/traits.d(105,30): Error: no property shouldEqual for type string
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/wrap/traits.d(108,30): Error: no property shouldEqual for type string
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/wrap/traits.d(111,30): Error: no property shouldEqual for type string
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/wrap/traits.d(114,30): Error: no property shouldEqual for type string
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/wrap/traits.d(117,30): Error: no property shouldEqual for type string
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/wrap/traits.d(120,32): Error: no property shouldEqual for type string
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/wrap/traits.d(124,32): Error: no property shouldEqual for type string
/home/laeeth/.dub/packages/excel-d-0.3.5/excel-d/source/xlld/wrap/wrap.d(509,19): Error: module `d_funcs` is in file 'test/d_funcs.d' which cannot be read

**Comment by atilaneves** [comment]
`dub test` doesn't actually do anything since there are no unit tests, only integration ones.
