### ISSUE TITLE
Nullable!T doesn't wrap

### ISSUE THREAD

**Issue by Laeeth** [kaleidicassociates/autowrap#3]
eg
skipping Nullable!(TDLine!(PriceBar!(PriceBarType(cast(PriceBarFlags)32u), -1, "Daily")))
skipping Nullable!(TDLine!(PriceBar!(PriceBarType(cast(PriceBarFlags)96u), -1, "Intraday")))
skipping Nullable!(KPDate!(cast(KPDateType)2, "Europe/London"))

**Comment by atilaneves** [comment]
The current version no longer skips `Nullable` at least when I tried it with `Nullable!int`. It does, however, crash, but that's a pyd bug.
